// examples/react-native/App.tsx
import React, { useState, useEffect } from 'react';
import {
  StyleSheet,
  View,
  ScrollView,
  SafeAreaView,
  StatusBar,
} from 'react-native';
import {
  Provider as PaperProvider,
  MD3LightTheme as DefaultTheme,
  Text,
  Card,
  TextInput,
  Button,
  Divider,
  SegmentedButtons,
  Badge,
  Chip,
} from 'react-native-paper';
import {
  FormStore,
  type DynamicFormSchema,
  type DynamicField,
  type FormState,
} from '@dynamic-form/core';

// Tipagem dos dados do formulário
export interface SupplierFormData {
  // Bloco 1: Identificação (dependentFields, clearedFieldsChanged, requiredFields, requiredRule)
  person_type: 'PF' | 'PJ';
  name: string;
  cpf?: string;
  cnpj?: string;
  corporate_name?: string;

  // Bloco 2: Localização (reloadFields, clearedFields)
  state_id: string;
  city_id: string;

  // Bloco 3: Fornecedor e Condições (disabledFields, disabledFieldsCondition)
  supplier_category: 'standard' | 'vip' | 'restricted';
  payment_terms: string;
  discount_percent: number;

  // Bloco 4: Pedido de Produto (autoSetFields, calcFields, requiredFields com 'and')
  product_id: string;
  product_sku: string;
  unit_price: number;
  quantity: number;
  total_price: number;
  warranty_months?: number;
}

// Importação do arquivo JSON universal único compartilhado em examples/
import formSchemaJson from '../form-schema.json';

// Extração dos catálogos de dados e do esquema a partir do JSON universal
export const PRODUCT_OPTIONS = formSchemaJson.catalogs.products;
export const CITIES_BY_STATE: Record<string, Array<{ label: string; value: string }>> =
  formSchemaJson.catalogs.cities_by_state;

// Esquema universal consumido diretamente do JSON único
export const supplierFormSchema = formSchemaJson as unknown as DynamicFormSchema<SupplierFormData>;

const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: '#1677ff',
    secondaryContainer: '#e6f4ff',
  },
};

export default function App() {
  const [store] = useState(
    () =>
      new FormStore<SupplierFormData>({
        schema: supplierFormSchema,
        initialValues: supplierFormSchema.default,
      }),
  );

  const [formState, setFormState] = useState(() => store.getState());
  const [submittedPayload, setSubmittedPayload] = useState<SupplierFormData | null>(null);

  useEffect(() => {
    return store.subscribe((next: FormState<SupplierFormData>) => {
      setFormState({ ...next });
    });
  }, [store]);

  const handleSubmit = async () => {
    const isValid = await store.validateForm();
    if (isValid) {
      setSubmittedPayload(store.getValues());
    }
  };

  const handleReset = () => {
    store.reset();
    setSubmittedPayload(null);
  };

  const { values, errors, visibility, disabledState, isDirty } = formState;

  // Lista dinâmica de cidades baseada no estado selecionado (reloadFields)
  const availableCities = values.state_id ? CITIES_BY_STATE[values.state_id] || [] : [];

  return (
    <PaperProvider theme={theme}>
      <SafeAreaView style={styles.safeArea}>
        <StatusBar barStyle="dark-content" backgroundColor="#f0f2f5" />
        <ScrollView contentContainerStyle={styles.container}>
          {/* Header */}
          <Card style={styles.headerCard} mode="elevated">
            <Card.Content>
              <View style={styles.headerRow}>
                <Text variant="titleLarge" style={styles.title}>
                  TESTE FINAL: 10 REGRAS
                </Text>
                <Badge style={[styles.badge, isDirty ? styles.badgeDirty : styles.badgeClean]}>
                  {isDirty ? 'Modificado' : 'Limpo'}
                </Badge>
              </View>
              <Text variant="bodyMedium" style={styles.subtitle}>
                Demonstração completa das 10 regras arquitetadas do DynamicField no React Native.
              </Text>
            </Card.Content>
          </Card>

          {/* Seção 1: Identificação */}
          <Card style={styles.sectionCard} mode="elevated">
            <Card.Content>
              <View style={styles.ruleBadgeRow}>
                <Chip icon="check-circle" compact style={styles.ruleChip}>
                  clearedFieldsChanged
                </Chip>
                <Chip icon="eye" compact style={styles.ruleChip}>
                  dependentFields
                </Chip>
                <Chip icon="alert" compact style={styles.ruleChip}>
                  requiredFields / requiredRule
                </Chip>
              </View>

              <Text variant="labelLarge" style={styles.sectionTitle}>
                1. Identificação do Fornecedor
              </Text>

              <Text variant="bodySmall" style={styles.fieldLabel}>
                Tipo de Pessoa (Dispara clearedFieldsChanged limpando CPF/CNPJ/Razão Social):
              </Text>
              <SegmentedButtons
                value={values.person_type}
                onValueChange={(val: string) => store.setValue('person_type', val as 'PF' | 'PJ')}
                buttons={[
                  { value: 'PF', label: 'Pessoa Física (PF)' },
                  { value: 'PJ', label: 'Pessoa Jurídica (PJ)' },
                ]}
                style={styles.segmented}
              />

              <TextInput
                label="Nome do Responsável *"
                mode="outlined"
                value={values.name ?? ''}
                error={Boolean(errors.name)}
                onChangeText={(text: string) => store.setValue('name', text)}
                style={styles.input}
              />
              {errors.name ? <Text style={styles.errorText}>{errors.name}</Text> : null}

              {/* CPF: dependentFields + requiredFields (PF) */}
              {visibility.cpf !== false && (
                <View style={styles.fieldBox}>
                  <TextInput
                    label={`CPF ${store.isFieldRequired('cpf') ? '*' : ''} (Exibido para PF)`}
                    mode="outlined"
                    value={values.cpf ?? ''}
                    keyboardType="numeric"
                    error={Boolean(errors.cpf)}
                    onChangeText={(text: string) => store.setValue('cpf', text)}
                    style={styles.input}
                  />
                  {errors.cpf ? <Text style={styles.errorText}>{errors.cpf}</Text> : null}
                  <Text variant="bodySmall" style={styles.hintText}>
                    💡 dependentFields: PF | requiredFields: PF | requiredRule: 'or'
                  </Text>
                </View>
              )}

              {/* CNPJ: dependentFields + requiredFields (PJ) */}
              {visibility.cnpj !== false && (
                <View style={styles.fieldBox}>
                  <TextInput
                    label={`CNPJ ${store.isFieldRequired('cnpj') ? '*' : ''} (Exibido para PJ)`}
                    mode="outlined"
                    value={values.cnpj ?? ''}
                    keyboardType="numeric"
                    error={Boolean(errors.cnpj)}
                    onChangeText={(text: string) => store.setValue('cnpj', text)}
                    style={styles.input}
                  />
                  {errors.cnpj ? <Text style={styles.errorText}>{errors.cnpj}</Text> : null}
                  <Text variant="bodySmall" style={styles.hintText}>
                    💡 dependentFields: PJ | requiredFields: PJ
                  </Text>
                </View>
              )}

              {/* Razão Social: dependentFields + clearedFields */}
              {visibility.corporate_name !== false && (
                <View style={styles.fieldBox}>
                  <TextInput
                    label="Razão Social (Exibido para PJ)"
                    mode="outlined"
                    value={values.corporate_name ?? ''}
                    onChangeText={(text: string) => store.setValue('corporate_name', text)}
                    style={styles.input}
                  />
                  <Text variant="bodySmall" style={styles.hintText}>
                    💡 dependentFields: PJ | clearedFields: ['person_type']
                  </Text>
                </View>
              )}
            </Card.Content>
          </Card>

          {/* Seção 2: Localização */}
          <Card style={styles.sectionCard} mode="elevated">
            <Card.Content>
              <View style={styles.ruleBadgeRow}>
                <Chip icon="refresh" compact style={styles.ruleChip}>
                  reloadFields
                </Chip>
                <Chip icon="eraser" compact style={styles.ruleChip}>
                  clearedFields
                </Chip>
              </View>

              <Text variant="labelLarge" style={styles.sectionTitle}>
                2. Localização Geográfica
              </Text>

              <Text variant="bodySmall" style={styles.fieldLabel}>
                Selecione o Estado (Gatilho de reloadFields e clearedFields para Cidade):
              </Text>
              <SegmentedButtons
                value={values.state_id}
                onValueChange={(val: string) => store.setValue('state_id', val)}
                buttons={[
                  { value: 'SP', label: 'São Paulo' },
                  { value: 'RJ', label: 'Rio de Janeiro' },
                  { value: 'MG', label: 'Minas Gerais' },
                ]}
                style={styles.segmented}
              />

              <Text variant="bodySmall" style={styles.fieldLabel}>
                Cidade (Limpa e recarregada via reloadFields quando o Estado muda):
              </Text>
              <SegmentedButtons
                value={values.city_id ?? ''}
                onValueChange={(val: string) => store.setValue('city_id', val)}
                buttons={availableCities.map((c) => ({
                  value: c.value,
                  label: c.label,
                }))}
                style={styles.segmented}
              />
              <Text variant="bodySmall" style={styles.hintText}>
                💡 Ao trocar o Estado, city_id é limpo e recarregado instantaneamente.
              </Text>
            </Card.Content>
          </Card>

          {/* Seção 3: Condições Comerciais */}
          <Card style={styles.sectionCard} mode="elevated">
            <Card.Content>
              <View style={styles.ruleBadgeRow}>
                <Chip icon="cancel" compact style={styles.ruleChip}>
                  disabledFields
                </Chip>
                <Chip icon="tune" compact style={styles.ruleChip}>
                  disabledFieldsCondition: 'and' | 'or'
                </Chip>
              </View>

              <Text variant="labelLarge" style={styles.sectionTitle}>
                3. Condições Comerciais & Descontos
              </Text>

              <Text variant="bodySmall" style={styles.fieldLabel}>
                Categoria do Fornecedor:
              </Text>
              <SegmentedButtons
                value={values.supplier_category}
                onValueChange={(val: string) =>
                  store.setValue('supplier_category', val as 'standard' | 'vip' | 'restricted')
                }
                buttons={[
                  { value: 'standard', label: 'Padrão' },
                  { value: 'vip', label: 'VIP' },
                  { value: 'restricted', label: 'Restrito' },
                ]}
                style={styles.segmented}
              />

              {/* Prazo de Pagamento: disabledFields com 'and' */}
              <Text variant="bodySmall" style={styles.fieldLabel}>
                Prazo de Pagamento (Desabilita apenas se Restrito E PF):
              </Text>
              <SegmentedButtons
                value={values.payment_terms}
                onValueChange={(val: string) => store.setValue('payment_terms', val)}
                buttons={[
                  { value: 'cash', label: 'À Vista', disabled: disabledState.payment_terms === true },
                  { value: '30_days', label: '30 Dias', disabled: disabledState.payment_terms === true },
                  { value: '60_days', label: '60 Dias', disabled: disabledState.payment_terms === true },
                ]}
                style={styles.segmented}
              />
              {disabledState.payment_terms === true && (
                <Text style={styles.disabledNotice}>
                  🔒 Bloqueado: Fornecedor Restrito e Pessoa Física (disabledFieldsCondition: 'and')
                </Text>
              )}

              {/* Desconto: disabledFields com 'or' */}
              <TextInput
                label="Desconto (%) (Desabilitado se Categoria for Restrito)"
                mode="outlined"
                keyboardType="numeric"
                value={String(values.discount_percent ?? '')}
                disabled={disabledState.discount_percent === true}
                onChangeText={(text: string) => store.setValue('discount_percent', Number(text) || 0)}
                style={[styles.input, disabledState.discount_percent === true ? styles.disabledInput : null]}
              />
              <Text variant="bodySmall" style={styles.hintText}>
                💡 disabledFields: {`{ supplier_category: 'restricted' }`} | disabledFieldsCondition: 'or'
              </Text>
            </Card.Content>
          </Card>

          {/* Seção 4: Pedido de Produto */}
          <Card style={styles.sectionCard} mode="elevated">
            <Card.Content>
              <View style={styles.ruleBadgeRow}>
                <Chip icon="lightning-bolt" compact style={styles.ruleChip}>
                  autoSetFields
                </Chip>
                <Chip icon="calculator" compact style={styles.ruleChip}>
                  calcFields (AST)
                </Chip>
              </View>

              <Text variant="labelLarge" style={styles.sectionTitle}>
                4. Pedido, AutoSet & Cálculo em Tempo Real
              </Text>

              <Text variant="bodySmall" style={styles.fieldLabel}>
                Selecione o Produto (Dispara autoSetFields preenchendo SKU e Preço):
              </Text>
              <View style={styles.productButtonCol}>
                {PRODUCT_OPTIONS.map((prod) => {
                  const isSelected = values.product_id === prod.value;
                  return (
                    <Button
                      key={prod.value}
                      mode={isSelected ? 'contained' : 'outlined'}
                      onPress={() => store.setValue('product_id', prod.value)}
                      style={styles.productBtn}
                    >
                      {prod.label}
                    </Button>
                  );
                })}
              </View>

              <View style={styles.row}>
                <TextInput
                  label="SKU (AutoSet)"
                  mode="outlined"
                  value={values.product_sku ?? ''}
                  disabled={true}
                  style={[styles.input, styles.halfInput, styles.disabledInput]}
                />
                <TextInput
                  label="Preço Unit. (AutoSet)"
                  mode="outlined"
                  value={`R$ ${values.unit_price ?? 0}`}
                  disabled={true}
                  style={[styles.input, styles.halfInput, styles.disabledInput]}
                />
              </View>

              <View style={styles.row}>
                <TextInput
                  label="Quantidade"
                  mode="outlined"
                  keyboardType="numeric"
                  value={String(values.quantity ?? '')}
                  onChangeText={(text: string) => store.setValue('quantity', Number(text) || 0)}
                  style={[styles.input, styles.halfInput]}
                />
                <TextInput
                  label="Desconto Aplicado"
                  mode="outlined"
                  value={`${values.discount_percent ?? 0}%`}
                  disabled={true}
                  style={[styles.input, styles.halfInput, styles.disabledInput]}
                />
              </View>

              {/* Total Calculado via AST */}
              <TextInput
                label="Valor Total Calculado (R$)"
                mode="outlined"
                value={`R$ ${values.total_price ?? 0}`}
                disabled={true}
                style={[styles.input, styles.totalInput]}
              />
              <Text variant="bodySmall" style={styles.hintText}>
                💡 calcFields: "#{`{quantity}# * #{unit_price}# * (1 - #{discount_percent}# / 100)`}"
              </Text>

              <Divider style={styles.divider} />

              {/* Garantia: requiredFields com 'and' */}
              <TextInput
                label={`Garantia Adicional (Meses) ${store.isFieldRequired('warranty_months') ? '* (Obrigatório)' : ''
                  }`}
                mode="outlined"
                keyboardType="numeric"
                placeholder="Ex: 12"
                value={values.warranty_months ? String(values.warranty_months) : ''}
                error={Boolean(errors.warranty_months)}
                onChangeText={(text: string) => store.setValue('warranty_months', Number(text) || undefined)}
                style={styles.input}
              />
              {errors.warranty_months ? (
                <Text style={styles.errorText}>{errors.warranty_months}</Text>
              ) : null}
              <Text variant="bodySmall" style={styles.hintText}>
                💡 requiredFields: {`{ supplier_category: 'vip', quantity: 5 }`} | requiredRule: 'and'
              </Text>
            </Card.Content>
          </Card>

          {/* Botões de Ação */}
          <View style={styles.actionButtons}>
            <Button
              mode="contained"
              onPress={handleSubmit}
              style={styles.submitBtn}
              icon="check"
            >
              Submeter Formulário
            </Button>
            <Button
              mode="outlined"
              onPress={handleReset}
              style={styles.resetBtn}
              icon="refresh"
            >
              Restaurar
            </Button>
          </View>

          {/* Card de Sucesso */}
          {submittedPayload && (
            <Card style={styles.resultCard} mode="elevated">
              <Card.Content>
                <Text variant="titleMedium" style={styles.resultTitle}>
                  ✅ Payload Validado e Submetido:
                </Text>
                <View style={styles.codeBlock}>
                  <Text style={styles.codeText}>
                    {JSON.stringify(submittedPayload, null, 2)}
                  </Text>
                </View>
              </Card.Content>
            </Card>
          )}

          {/* Inspetor de Estado do DAG Engine */}
          <Card style={styles.stateCard} mode="outlined">
            <Card.Content>
              <Text variant="titleSmall" style={styles.stateTitle}>
                🔍 Inspetor de Estado em Tempo Real:
              </Text>
              <Text variant="bodySmall">
                • Total Calculado: <Text style={styles.bold}>{values.total_price}</Text>
              </Text>
              <Text variant="bodySmall">
                • SKU AutoSet: <Text style={styles.bold}>{values.product_sku}</Text>
              </Text>
              <Text variant="bodySmall">
                • Visibilidade CPF: <Text style={styles.bold}>{String(visibility.cpf !== false)}</Text> | CNPJ:{' '}
                <Text style={styles.bold}>{String(visibility.cnpj !== false)}</Text>
              </Text>
              <Text variant="bodySmall">
                • Prazo Pagamento Desabilitado:{' '}
                <Text style={styles.bold}>{String(disabledState.payment_terms === true)}</Text>
              </Text>
              <Text variant="bodySmall">
                • Desconto Desabilitado:{' '}
                <Text style={styles.bold}>{String(disabledState.discount_percent === true)}</Text>
              </Text>
              <Text variant="bodySmall">
                • Garantia Obrigatória:{' '}
                <Text style={styles.bold}>{String(store.isFieldRequired('warranty_months'))}</Text>
              </Text>
              <Text variant="bodySmall">
                • Formulário Dirty: <Text style={styles.bold}>{String(isDirty)}</Text>
              </Text>
            </Card.Content>
          </Card>
        </ScrollView>
      </SafeAreaView>
    </PaperProvider>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f0f2f5' },
  container: { padding: 16, paddingBottom: 40 },
  headerCard: { marginBottom: 16, backgroundColor: '#ffffff', borderRadius: 12 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  title: { fontWeight: 'bold', color: '#1677ff' },
  subtitle: { color: '#666666', marginTop: 4 },
  badge: { paddingHorizontal: 8, fontSize: 12 },
  badgeClean: { backgroundColor: '#52c41a' },
  badgeDirty: { backgroundColor: '#faad14' },
  sectionCard: { backgroundColor: '#ffffff', borderRadius: 12, marginBottom: 16 },
  sectionTitle: { fontWeight: 'bold', color: '#1677ff', marginBottom: 10, marginTop: 4 },
  ruleBadgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 8 },
  ruleChip: { backgroundColor: '#f0f5ff' },
  fieldLabel: { fontWeight: '600', marginBottom: 6, color: '#333333' },
  segmented: { marginBottom: 12 },
  input: { marginBottom: 8, backgroundColor: '#ffffff' },
  disabledInput: { backgroundColor: '#f5f5f5' },
  halfInput: { flex: 1, marginHorizontal: 4 },
  totalInput: { backgroundColor: '#e6f7ff', fontWeight: 'bold' },
  row: { flexDirection: 'row', marginHorizontal: -4 },
  fieldBox: { marginVertical: 4 },
  hintText: { color: '#888888', fontStyle: 'italic', marginBottom: 8, marginLeft: 2 },
  disabledNotice: { color: '#fa8c16', fontSize: 12, marginBottom: 8, fontStyle: 'italic' },
  errorText: { color: '#ff4d4f', fontSize: 12, marginBottom: 8, marginLeft: 4 },
  divider: { marginVertical: 14 },
  productButtonCol: { gap: 8, marginBottom: 12 },
  productBtn: { borderRadius: 8 },
  actionButtons: { flexDirection: 'row', gap: 10, marginTop: 4, marginBottom: 16 },
  submitBtn: { flex: 2, borderRadius: 8 },
  resetBtn: { flex: 1, borderRadius: 8 },
  resultCard: { backgroundColor: '#f6ffed', borderColor: '#b7eb8f', borderWidth: 1, borderRadius: 12, marginBottom: 16 },
  resultTitle: { color: '#389e0d', fontWeight: 'bold', marginBottom: 8 },
  codeBlock: { backgroundColor: '#ffffff', padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#d9d9d9' },
  codeText: { fontFamily: 'monospace', fontSize: 12, color: '#262626' },
  stateCard: { backgroundColor: '#fafafa', borderRadius: 12 },
  stateTitle: { fontWeight: 'bold', marginBottom: 6, color: '#595959' },
  bold: { fontWeight: 'bold', color: '#1677ff' },
});

// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useDynamicForm } from './composables/useDynamicForm';
import schemaData from './form-schema.json';

const schema = schemaData;
const submitSuccess = ref(false);
const lastSubmittedPayload = ref<any>(null);

const { state, setValue, submit, reset, isFieldRequired } = useDynamicForm({
  schema: schema as any,
  onSubmit: (values) => {
    lastSubmittedPayload.value = values;
    submitSuccess.value = true;
    setTimeout(() => {
      submitSuccess.value = false;
    }, 5000);
  },
});

// Opções dinâmicas de cidades pelo estado selecionado
const availableCities = computed(() => {
  const currentState = state.value.values['state_id'];
  const citiesCatalog = (schema.catalogs as any)?.cities_by_state || {};
  return citiesCatalog[currentState] || [];
});

function onInputChange(field: string, event: Event, isNumber = false) {
  const input = event.target as HTMLInputElement;
  const rawVal = input.value;
  if (isNumber) {
    setValue(field, rawVal === '' ? null : Number(rawVal));
  } else {
    setValue(field, rawVal);
  }
}

function onSelectChange(field: string, event: Event) {
  const select = event.target as HTMLSelectElement;
  setValue(field, select.value);
}

function selectProduct(productId: string) {
  setValue('product_id', productId);
}

function setPersonType(type: 'PF' | 'PJ') {
  setValue('person_type', type);
}

function setSupplierCategory(category: 'standard' | 'vip' | 'restricted') {
  setValue('supplier_category', category);
}

async function handleSubmit() {
  await submit();
}

function handleReset() {
  lastSubmittedPayload.value = null;
  submitSuccess.value = false;
  reset();
}

function formatCurrency(val: number | null | undefined): string {
  if (val === null || val === undefined || isNaN(val)) return 'R$ 0,00';
  return Number(val).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
}
</script>

<template>
  <div class="app-layout">
    <!-- Header -->
    <header class="app-header">
      <div class="header-container">
        <div class="brand-row">
          <span class="tech-badge">Vue 3 + Composition API</span>
          <span class="engine-badge">&#64;dynamic-form/core</span>
          <span class="status-badge" :class="{ dirty: state.isDirty }">
            {{ state.isDirty ? '● Não Salvo (Dirty)' : '✓ Sincronizado' }}
          </span>
        </div>
        <h1 class="app-title">{{ schema.title }}</h1>
        <p class="app-subtitle">{{ schema.subtitle }}</p>
      </div>
    </header>

    <main class="main-container">
      <!-- Feedback de Sucesso no Envio -->
      <transition name="fade">
        <div v-if="submitSuccess" class="alert-success">
          <div class="alert-icon">✓</div>
          <div>
            <strong>Formulário Validado e Submetido com Sucesso!</strong>
            <p>Todos os campos obrigatórios e regras ativas foram respeitados pelo &#64;dynamic-form/core.</p>
          </div>
        </div>
      </transition>

      <form @submit.prevent="handleSubmit" class="form-grid">
        <!-- Seção 1: Identificação -->
        <section class="card section-card">
          <div class="card-header">
            <div class="section-title-wrap">
              <span class="section-num">1</span>
              <div>
                <h2 class="section-title">Identificação do Contato</h2>
                <p class="section-desc">Validação condicional de documentos e limpeza reativa</p>
              </div>
            </div>
            <div class="chip-group">
              <span class="chip">dependentFields</span>
              <span class="chip">requiredFields</span>
              <span class="chip">clearedFieldsChanged</span>
            </div>
          </div>

          <div class="card-body">
            <div class="form-row">
              <!-- Tipo de Pessoa -->
              <div class="form-group flex-1">
                <label class="field-label">Tipo de Pessoa</label>
                <div class="segmented-control">
                  <button
                    type="button"
                    class="segment-btn"
                    :class="{ active: state.values['person_type'] === 'PF' }"
                    @click="setPersonType('PF')"
                  >
                    Pessoa Física (PF)
                  </button>
                  <button
                    type="button"
                    class="segment-btn"
                    :class="{ active: state.values['person_type'] === 'PJ' }"
                    @click="setPersonType('PJ')"
                  >
                    Pessoa Jurídica (PJ)
                  </button>
                </div>
                <small class="field-hint">💡 clearedFieldsChanged limpa CPF/CNPJ na troca de tipo</small>
              </div>

              <!-- Nome de Contato -->
              <div class="form-group flex-1">
                <label class="field-label" :class="{ required: isFieldRequired('name') }">
                  Nome de Contato <span v-if="isFieldRequired('name')" class="req-star">*</span>
                </label>
                <input
                  type="text"
                  class="form-control"
                  :class="{ 'has-error': state.errors['name'] }"
                  :value="state.values['name'] || ''"
                  @input="e => onInputChange('name', e)"
                  placeholder="Ex: João Silva"
                />
                <span v-if="state.errors['name']" class="error-msg">{{ state.errors['name'] }}</span>
              </div>
            </div>

            <div class="form-row">
              <!-- CPF (Visível se PF) -->
              <div class="form-group flex-1" v-if="state.visibility['cpf'] !== false">
                <label class="field-label" :class="{ required: isFieldRequired('cpf') }">
                  CPF (Pessoa Física) <span v-if="isFieldRequired('cpf')" class="req-star">*</span>
                </label>
                <input
                  type="text"
                  class="form-control"
                  :class="{ 'has-error': state.errors['cpf'] }"
                  :value="state.values['cpf'] || ''"
                  @input="e => onInputChange('cpf', e)"
                  placeholder="000.000.000-00"
                />
                <span v-if="state.errors['cpf']" class="error-msg">{{ state.errors['cpf'] }}</span>
                <small class="field-hint">💡 dependentFields: person_type === 'PF'</small>
              </div>

              <!-- CNPJ (Visível se PJ) -->
              <div class="form-group flex-1" v-if="state.visibility['cnpj'] !== false">
                <label class="field-label" :class="{ required: isFieldRequired('cnpj') }">
                  CNPJ (Pessoa Jurídica) <span v-if="isFieldRequired('cnpj')" class="req-star">*</span>
                </label>
                <input
                  type="text"
                  class="form-control"
                  :class="{ 'has-error': state.errors['cnpj'] }"
                  :value="state.values['cnpj'] || ''"
                  @input="e => onInputChange('cnpj', e)"
                  placeholder="00.000.000/0001-00"
                />
                <span v-if="state.errors['cnpj']" class="error-msg">{{ state.errors['cnpj'] }}</span>
                <small class="field-hint">💡 dependentFields: person_type === 'PJ'</small>
              </div>

              <!-- Razão Social (Visível se PJ) -->
              <div class="form-group flex-1" v-if="state.visibility['corporate_name'] !== false">
                <label class="field-label">Razão Social</label>
                <input
                  type="text"
                  class="form-control"
                  :value="state.values['corporate_name'] || ''"
                  @input="e => onInputChange('corporate_name', e)"
                  placeholder="Ex: Create Pixels LTDA"
                />
                <small class="field-hint">💡 clearedFields: ['person_type']</small>
              </div>
            </div>
          </div>
        </section>

        <!-- Seção 2: Localização -->
        <section class="card section-card">
          <div class="card-header">
            <div class="section-title-wrap">
              <span class="section-num">2</span>
              <div>
                <h2 class="section-title">Localização Geográfica</h2>
                <p class="section-desc">Recarga e reset de dados em cascata</p>
              </div>
            </div>
            <div class="chip-group">
              <span class="chip">reloadFields</span>
              <span class="chip">clearedFields</span>
            </div>
          </div>

          <div class="card-body">
            <div class="form-row">
              <!-- Estado -->
              <div class="form-group flex-1">
                <label class="field-label">Estado (UF)</label>
                <select
                  class="form-control"
                  :value="state.values['state_id'] || ''"
                  @change="e => onSelectChange('state_id', e)"
                >
                  <option value="SP">São Paulo (SP)</option>
                  <option value="RJ">Rio de Janeiro (RJ)</option>
                  <option value="MG">Minas Gerais (MG)</option>
                </select>
              </div>

              <!-- Cidade -->
              <div class="form-group flex-1">
                <label class="field-label">Cidade</label>
                <select
                  class="form-control"
                  :value="state.values['city_id'] || ''"
                  @change="e => onSelectChange('city_id', e)"
                >
                  <option value="" disabled>Selecione uma cidade...</option>
                  <option v-for="c in availableCities" :key="c.value" :value="c.value">
                    {{ c.label }}
                  </option>
                </select>
                <small class="field-hint">💡 reloadFields: [state_id] | clearedFields: [state_id]</small>
              </div>
            </div>
          </div>
        </section>

        <!-- Seção 3: Condições Comerciais -->
        <section class="card section-card">
          <div class="card-header">
            <div class="section-title-wrap">
              <span class="section-num">3</span>
              <div>
                <h2 class="section-title">Condições Comerciais</h2>
                <p class="section-desc">Bloqueio dinâmico com operadores booleanos AND e OR</p>
              </div>
            </div>
            <div class="chip-group">
              <span class="chip">disabledFields</span>
              <span class="chip">disabledFieldsCondition: and/or</span>
            </div>
          </div>

          <div class="card-body">
            <div class="form-row">
              <!-- Categoria do Fornecedor -->
              <div class="form-group flex-1">
                <label class="field-label">Categoria do Fornecedor</label>
                <div class="segmented-control">
                  <button
                    type="button"
                    class="segment-btn"
                    :class="{ active: state.values['supplier_category'] === 'standard' }"
                    @click="setSupplierCategory('standard')"
                  >
                    Padrão
                  </button>
                  <button
                    type="button"
                    class="segment-btn"
                    :class="{ active: state.values['supplier_category'] === 'vip' }"
                    @click="setSupplierCategory('vip')"
                  >
                    VIP (Grandes Contas)
                  </button>
                  <button
                    type="button"
                    class="segment-btn"
                    :class="{ active: state.values['supplier_category'] === 'restricted' }"
                    @click="setSupplierCategory('restricted')"
                  >
                    Restrito (Bloqueado)
                  </button>
                </div>
              </div>

              <!-- Prazo de Pagamento -->
              <div class="form-group flex-1">
                <label class="field-label">
                  Prazo de Pagamento
                  <span v-if="state.disabledState['payment_terms']" class="lock-indicator">🔒 Bloqueado</span>
                </label>
                <select
                  class="form-control"
                  :value="state.values['payment_terms'] || ''"
                  :disabled="state.disabledState['payment_terms'] === true"
                  @change="e => onSelectChange('payment_terms', e)"
                >
                  <option value="cash">À Vista</option>
                  <option value="30_days">Boleto 30 Dias</option>
                  <option value="60_days">Boleto 60 Dias</option>
                </select>
                <small class="field-hint">💡 Bloqueia se supplier_category === 'restricted' AND person_type === 'PF'</small>
              </div>

              <!-- Desconto (%) -->
              <div class="form-group flex-1">
                <label class="field-label">
                  Desconto (%)
                  <span v-if="state.disabledState['discount_percent']" class="lock-indicator">🔒 Bloqueado</span>
                </label>
                <input
                  type="number"
                  class="form-control"
                  min="0"
                  max="100"
                  :value="state.values['discount_percent'] ?? ''"
                  :disabled="state.disabledState['discount_percent'] === true"
                  @input="e => onInputChange('discount_percent', e, true)"
                />
                <small class="field-hint">💡 Bloqueia se supplier_category === 'restricted' (OR)</small>
              </div>
            </div>
          </div>
        </section>

        <!-- Seção 4: Catálogo & Aritmética -->
        <section class="card section-card">
          <div class="card-header">
            <div class="section-title-wrap">
              <span class="section-num">4</span>
              <div>
                <h2 class="section-title">Catálogo & Cálculo em Cascata</h2>
                <p class="section-desc">autoSetFields com record e calcFields sem eval()</p>
              </div>
            </div>
            <div class="chip-group">
              <span class="chip">autoSetFields</span>
              <span class="chip">calcFields</span>
              <span class="chip">requiredRule: and</span>
            </div>
          </div>

          <div class="card-body">
            <label class="field-label">Selecione um Produto do Catálogo (Dispara autoSetFields):</label>
            <div class="catalog-cards">
              <button
                type="button"
                class="catalog-item"
                v-for="prod in (schema.catalogs as any)?.products"
                :key="prod.value"
                :class="{ selected: state.values['product_id'] === prod.value }"
                @click="selectProduct(prod.value)"
              >
                <div class="item-title">{{ prod.label }}</div>
                <div class="item-sub">SKU: {{ prod.record?.sku }} • {{ formatCurrency(prod.record?.price) }}</div>
              </button>
            </div>

            <div class="form-row mt-3">
              <div class="form-group flex-1">
                <label class="field-label">SKU Derivado (autoSetFields)</label>
                <input type="text" class="form-control bg-readonly" :value="state.values['product_sku'] || ''" disabled />
              </div>

              <div class="form-group flex-1">
                <label class="field-label">Preço Unitário (R$)</label>
                <input type="text" class="form-control bg-readonly" :value="formatCurrency(state.values['unit_price'])" disabled />
              </div>

              <div class="form-group flex-1">
                <label class="field-label">Quantidade</label>
                <input
                  type="number"
                  class="form-control"
                  min="1"
                  :value="state.values['quantity'] ?? 1"
                  @input="e => onInputChange('quantity', e, true)"
                />
              </div>
            </div>

            <!-- Banner de Total Calculado -->
            <div class="calc-banner">
              <div class="calc-info">
                <span class="calc-label">Total Calculado em Tempo Real (AST Parser)</span>
                <code class="calc-formula">
                  {{ state.values['quantity'] || 0 }} un × {{ formatCurrency(state.values['unit_price']) }} × (1 - {{ state.values['discount_percent'] || 0 }}%)
                </code>
              </div>
              <div class="calc-value">
                {{ formatCurrency(state.values['total_price']) }}
              </div>
            </div>

            <div class="form-row mt-3">
              <!-- Garantia Adicional -->
              <div class="form-group flex-1">
                <label class="field-label" :class="{ required: isFieldRequired('warranty_months') }">
                  Garantia Adicional (Meses)
                  <span v-if="isFieldRequired('warranty_months')" class="req-star">*</span>
                </label>
                <input
                  type="number"
                  class="form-control"
                  :class="{ 'has-error': state.errors['warranty_months'] }"
                  :value="state.values['warranty_months'] ?? ''"
                  @input="e => onInputChange('warranty_months', e, true)"
                  placeholder="Ex: 12"
                />
                <span v-if="state.errors['warranty_months']" class="error-msg">{{ state.errors['warranty_months'] }}</span>
                <small class="field-hint">
                  ⚠️ Obrigatório via operador AND se Categoria = 'VIP' E Quantidade = 5!
                </small>
              </div>
            </div>
          </div>
        </section>

        <!-- Barra de Ações -->
        <div class="actions-bar">
          <button type="button" class="btn btn-secondary" @click="handleReset">
            ↺ {{ (schema.actions as any)?.resetText || 'Restaurar' }}
          </button>
          <button type="submit" class="btn btn-primary" :disabled="state.isSubmitting">
            ✓ {{ (schema.actions as any)?.submitText || 'Submeter Formulário' }}
          </button>
        </div>
      </form>

      <!-- Inspetor de Estado Reativo (JSON Debugger) -->
      <section class="card inspector-card mt-4">
        <div class="card-header">
          <h3 class="inspector-title">🔍 Inspetor de Estado Vue 3 (Composition API)</h3>
          <span class="inspector-badge">Tempo Real</span>
        </div>
        <div class="card-body inspector-body">
          <div class="inspector-col">
            <h4>Valores (values)</h4>
            <pre>{{ JSON.stringify(state.values, null, 2) }}</pre>
          </div>
          <div class="inspector-col">
            <h4>Erros (errors)</h4>
            <pre>{{ JSON.stringify(state.errors, null, 2) }}</pre>
          </div>
          <div class="inspector-col">
            <h4>Visibilidade & Bloqueios</h4>
            <pre>{{ JSON.stringify({ visibility: state.visibility, disabled: state.disabledState }, null, 2) }}</pre>
          </div>
        </div>
      </section>
    </main>
  </div>
</template>

<style scoped>
.app-layout {
  min-height: 100vh;
  background-color: #0f172a;
  color: #f8fafc;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
  padding-bottom: 48px;
}

/* Header */
.app-header {
  background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
  border-bottom: 1px solid rgba(255, 255, 255, 0.08);
  padding: 32px 16px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.25);
}

.header-container {
  max-width: 900px;
  margin: 0 auto;
}

.brand-row {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 12px;
  flex-wrap: wrap;
}

.tech-badge {
  background: linear-gradient(135deg, #42b883 0%, #35495e 100%);
  color: white;
  font-size: 11px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  padding: 4px 10px;
  border-radius: 9999px;
  box-shadow: 0 2px 8px rgba(66, 184, 131, 0.3);
}

.engine-badge {
  background: #334155;
  color: #38bdf8;
  font-size: 11px;
  font-weight: 600;
  padding: 4px 10px;
  border-radius: 9999px;
  border: 1px solid rgba(56, 189, 248, 0.2);
}

.status-badge {
  background: rgba(34, 197, 94, 0.15);
  color: #4ade80;
  border: 1px solid rgba(34, 197, 94, 0.3);
  font-size: 11px;
  font-weight: 600;
  padding: 4px 10px;
  border-radius: 9999px;
}

.status-badge.dirty {
  background: rgba(245, 158, 11, 0.15);
  color: #fbbf24;
  border-color: rgba(245, 158, 11, 0.3);
}

.app-title {
  font-size: 26px;
  font-weight: 800;
  margin: 0 0 6px 0;
  letter-spacing: -0.5px;
  background: linear-gradient(to right, #ffffff, #94a3b8);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.app-subtitle {
  font-size: 14px;
  color: #94a3b8;
  margin: 0;
}

/* Main Container */
.main-container {
  max-width: 900px;
  margin: 28px auto 0 auto;
  padding: 0 16px;
}

/* Alert Success */
.alert-success {
  display: flex;
  align-items: center;
  gap: 16px;
  background: rgba(16, 185, 129, 0.12);
  border: 1px solid rgba(16, 185, 129, 0.3);
  color: #a7f3d0;
  padding: 16px 20px;
  border-radius: 12px;
  margin-bottom: 24px;
}

.alert-icon {
  background: #10b981;
  color: #064e3b;
  width: 32px;
  height: 32px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: bold;
  font-size: 16px;
  flex-shrink: 0;
}

.alert-success strong {
  display: block;
  font-size: 15px;
  color: #ecfdf5;
  margin-bottom: 2px;
}

.alert-success p {
  margin: 0;
  font-size: 13px;
  color: #6ee7b7;
}

/* Form Grid */
.form-grid {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

/* Cards */
.card {
  background: #1e293b;
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 16px;
  overflow: hidden;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.2);
  transition: transform 0.2s ease, border-color 0.2s ease;
}

.card:hover {
  border-color: rgba(255, 255, 255, 0.15);
}

.card-header {
  padding: 18px 22px;
  background: rgba(15, 23, 42, 0.6);
  border-bottom: 1px solid rgba(255, 255, 255, 0.06);
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 12px;
}

.section-title-wrap {
  display: flex;
  align-items: center;
  gap: 14px;
}

.section-num {
  width: 28px;
  height: 28px;
  background: #10b981;
  color: white;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 800;
  font-size: 13px;
}

.section-title {
  font-size: 17px;
  font-weight: 700;
  margin: 0 0 2px 0;
  color: #f1f5f9;
}

.section-desc {
  font-size: 12px;
  color: #94a3b8;
  margin: 0;
}

.chip-group {
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
}

.chip {
  background: rgba(16, 185, 129, 0.12);
  color: #6ee7b7;
  border: 1px solid rgba(16, 185, 129, 0.25);
  font-size: 11px;
  font-weight: 600;
  padding: 3px 8px;
  border-radius: 6px;
}

.card-body {
  padding: 22px;
}

/* Form Controls */
.form-row {
  display: flex;
  gap: 16px;
  flex-wrap: wrap;
  margin-bottom: 16px;
}

.form-row:last-child {
  margin-bottom: 0;
}

.flex-1 {
  flex: 1;
  min-width: 240px;
}

.form-group {
  display: flex;
  flex-direction: column;
}

.field-label {
  font-size: 13px;
  font-weight: 600;
  color: #cbd5e1;
  margin-bottom: 8px;
  display: flex;
  align-items: center;
  gap: 6px;
}

.req-star {
  color: #ef4444;
}

.lock-indicator {
  font-size: 11px;
  background: rgba(239, 68, 68, 0.15);
  color: #fca5a5;
  padding: 2px 6px;
  border-radius: 4px;
}

.form-control {
  background: #0f172a;
  border: 1px solid #334155;
  color: #f8fafc;
  padding: 11px 14px;
  border-radius: 10px;
  font-size: 14px;
  outline: none;
  transition: all 0.2s ease;
  width: 100%;
  box-sizing: border-box;
}

.form-control:focus {
  border-color: #10b981;
  box-shadow: 0 0 0 3px rgba(16, 185, 129, 0.2);
}

.form-control:disabled {
  background: #1e293b;
  color: #64748b;
  cursor: not-allowed;
  border-color: rgba(255, 255, 255, 0.05);
}

.form-control.has-error {
  border-color: #ef4444;
  background: rgba(239, 68, 68, 0.05);
}

.bg-readonly {
  background: rgba(15, 23, 42, 0.5) !important;
  font-weight: 600;
  color: #94a3b8;
}

.error-msg {
  color: #f87171;
  font-size: 12px;
  margin-top: 6px;
  font-weight: 500;
}

.field-hint {
  color: #64748b;
  font-size: 11px;
  margin-top: 6px;
}

/* Segmented Control */
.segmented-control {
  display: flex;
  background: #0f172a;
  padding: 4px;
  border-radius: 10px;
  border: 1px solid #334155;
  gap: 4px;
}

.segment-btn {
  flex: 1;
  background: transparent;
  border: none;
  color: #94a3b8;
  padding: 8px 12px;
  border-radius: 7px;
  font-size: 13px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s ease;
}

.segment-btn.active {
  background: #10b981;
  color: white;
  box-shadow: 0 2px 6px rgba(16, 185, 129, 0.4);
}

/* Catalog Cards */
.catalog-cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 12px;
  margin-bottom: 16px;
}

.catalog-item {
  background: #0f172a;
  border: 1px solid #334155;
  padding: 14px 16px;
  border-radius: 12px;
  text-align: left;
  cursor: pointer;
  transition: all 0.2s ease;
}

.catalog-item:hover {
  border-color: #10b981;
  background: rgba(16, 185, 129, 0.05);
}

.catalog-item.selected {
  border-color: #10b981;
  background: rgba(16, 185, 129, 0.12);
  box-shadow: 0 0 0 1px #10b981;
}

.item-title {
  color: #f1f5f9;
  font-weight: 700;
  font-size: 14px;
  margin-bottom: 4px;
}

.item-sub {
  color: #94a3b8;
  font-size: 12px;
}

/* Calc Banner */
.calc-banner {
  background: linear-gradient(135deg, rgba(6, 78, 59, 0.4) 0%, rgba(15, 23, 42, 0.7) 100%);
  border: 1px solid rgba(16, 185, 129, 0.35);
  border-radius: 14px;
  padding: 18px 22px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  flex-wrap: wrap;
  margin-top: 18px;
}

.calc-info {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.calc-label {
  font-size: 12px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: #34d399;
}

.calc-formula {
  font-family: 'JetBrains Mono', Courier, monospace;
  font-size: 13px;
  color: #a7f3d0;
}

.calc-value {
  font-size: 26px;
  font-weight: 800;
  color: #4ade80;
  letter-spacing: -0.5px;
}

/* Action Buttons */
.actions-bar {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  margin-top: 10px;
}

.btn {
  padding: 13px 26px;
  border-radius: 10px;
  font-size: 14px;
  font-weight: 700;
  cursor: pointer;
  border: none;
  transition: all 0.2s ease;
}

.btn-secondary {
  background: #334155;
  color: #e2e8f0;
}

.btn-secondary:hover {
  background: #475569;
}

.btn-primary {
  background: linear-gradient(135deg, #10b981 0%, #059669 100%);
  color: white;
  box-shadow: 0 4px 14px rgba(16, 185, 129, 0.35);
}

.btn-primary:hover {
  background: linear-gradient(135deg, #059669 0%, #047857 100%);
  box-shadow: 0 6px 18px rgba(16, 185, 129, 0.45);
  transform: translateY(-1px);
}

/* Inspector */
.inspector-card {
  margin-top: 36px;
  border-color: rgba(255, 255, 255, 0.05);
}

.inspector-title {
  font-size: 14px;
  font-weight: 700;
  margin: 0;
  color: #cbd5e1;
}

.inspector-badge {
  font-size: 11px;
  background: rgba(56, 189, 248, 0.15);
  color: #38bdf8;
  padding: 2px 8px;
  border-radius: 6px;
}

.inspector-body {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 16px;
  padding: 16px;
}

.inspector-col h4 {
  font-size: 12px;
  color: #64748b;
  text-transform: uppercase;
  margin: 0 0 8px 0;
  letter-spacing: 0.5px;
}

.inspector-col pre {
  background: #090d16;
  padding: 12px;
  border-radius: 8px;
  font-family: 'JetBrains Mono', Courier, monospace;
  font-size: 11px;
  color: #a5f3fc;
  overflow-x: auto;
  border: 1px solid rgba(255, 255, 255, 0.05);
  max-height: 220px;
}

.mt-3 { margin-top: 16px; }
.mt-4 { margin-top: 24px; }

.fade-enter-active, .fade-leave-active {
  transition: opacity 0.3s ease;
}
.fade-enter-from, .fade-leave-to {
  opacity: 0;
}
</style>
